# 📄 .github/workflows/update-mta-sts-id.yml

name: Update MTA-STS DNS ID

# 🔁 Trigger: Nur wenn mta-sts.txt sich ändert
on:
  push:
    paths:
      - ".well-known/mta-sts.txt"

jobs:
  update-mta-sts-id:
    name: Update _mta-sts DNS Record
    runs-on: windows-latest

    steps:
      # 📥 Repository klonen
      - name: Checkout repo
        uses: actions/checkout@v4

      # ⏱️ Erzeuge neuen Zeitstempel für DNS ID
      - name: Generate timestamp ID
        id: timestamp
        run: echo "::set-output name=id::$(Get-Date -Format yyyyMMddTHHmmss)"
        shell: pwsh

      # 📤 DNS-Record bei Cloudflare updaten
      - name: Update Cloudflare DNS TXT record
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}       # Cloudflare API Token
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}           # Cloudflare Zone ID
          CF_RECORD_ID: ${{ secrets.CF_RECORD_ID }}       # DNS Record ID für _mta-sts
        run: |
          $Headers = @{ 
            "Authorization" = "Bearer $env:CF_API_TOKEN" 
            "Content-Type"  = "application/json" 
          }

          $NewContent = '"v=STSv1; id=${{ steps.timestamp.outputs.id }}"'

          $Body = @{ 
            type = "TXT"
            name = "_mta-sts.remsy.net"
            content = $NewContent
            ttl = 3600 
          } | ConvertTo-Json -Depth 3

          Invoke-RestMethod -Uri "https://api.cloudflare.com/client/v4/zones/$env:CF_ZONE_ID/dns_records/$env:CF_RECORD_ID" -Method PUT -Headers $Headers -Body $Body
        shell: pwsh
